modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "Unlicense"

[[mods]]
modId = "example_mod"
version = "${version}"
displayName = "Example Mod"
authors = "Author"
description = '''
Mod Description
'''
# logoFile = ""

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.example_mod]]
modId = "neoforge"
type = "required"
versionRange = "[26.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.example_mod]]
modId = "minecraft"
type = "required"
versionRange = "[26.1,)"
ordering = "NONE"
side = "BOTH"


[[mixins]]
config = "example_mod.mixins.json"
